---
header: |
  # frozen_string_literal: false

  require 'simplecov'

  ::SimpleCov.command_name 'Brutal test suite'
  ::SimpleCov.start

  require './lib/sashite-gan'

subject: |
  Sashite::GAN.parse("%{string}")

contexts:
  string:
    - C:R
    - c:-k
    - M:B
    - s:-k
    - S:-K
    - S:+P
    - X:-G
    - X:+-G
    - DAI_DAI_SHOGI:PH
    - FOO:+Z

actuals:
  - "(%{subject} == \"C:R\")"
  - "%{subject}.eql?(\"C:R\")"
  - "(%{subject} == Sashite::GAN.parse(\"C:R\"))"
  - "%{subject}.eql?(Sashite::GAN.parse(\"C:R\"))"
  - "%{subject}.inspect.to_s"
  - "%{subject}.class.inspect"
  - "(%{subject}.abbr == \"R\")"
  - "%{subject}.abbr.eql?(\"R\")"
  - "(%{subject}.abbr == Sashite::GAN.parse(\"C:R\").abbr)"
  - "%{subject}.abbr.eql?(Sashite::GAN.parse(\"C:R\").abbr)"
  - "%{subject}.abbr.inspect.to_s"
  - "%{subject}.abbr.to_s"
  - "%{subject}.style"
  - "%{subject}.king?"
  - "%{subject}.topside?"
  - "%{subject}.bottomside?"
  - "%{subject}.to_s"
  - "%{subject}.topside.to_s"
  - "%{subject}.topside.class.inspect"
  - "%{subject}.bottomside.to_s"
  - "%{subject}.bottomside.class.inspect"
  - "%{subject}.oppositeside.to_s"
  - "%{subject}.oppositeside.class.inspect"
  - "%{subject}.promote.to_s"
  - "%{subject}.promote.class.inspect"
  - "%{subject}.unpromote.to_s"
  - "%{subject}.unpromote.class.inspect"
